In [17]:
#Numpy is the core library for scientific computing in Python. It provides a high performance multidimensional
#array object, and tools for working with these arrays. This will be a quick review since I am already used with Matlab

#Arrays
#A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non negative integers.
#The number of the dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size
#of the array in each dimension

import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

# Numpy provides many functions to create arrays

#Creates an array with zeroes only
a = np.zeros((2,2))
print(a)

#Create an array with ones only
b = np.ones((1,2))
print(b)

#Create a constant array
c = np.full((2,2), 7)
print(c)

#Creates a 2x2 identity matrix
d = np.eye(2)
print(d)

#Creates an array filled with random values
e = np.random.random((2,2))
print(e)



<class 'numpy.ndarray'>
(3,)
[1 2 3]
1 2 3
[5 2 3]
(2, 3)
1 2 4
[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.71994901  0.48716566]
 [ 0.56880443  0.54297855]]


In [26]:
# Array indexing with numpy

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]

b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0,1])
print(a[0,:])
b[0,0] = 77
print(a[0,1])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
[1 2 3 4]
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:

row_r1 = a[1, :]   #Rank 1 view of the second row of a
row_r2 = a[1:2, :] #Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

#Distinctions may be made when accessing columns of an array

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [35]:
#Integer array indexing

#Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always
#be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary 
#arrays using the data from another array.


a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"


[1 4 5]


In [44]:
#Mutating one element of a matrix

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)

# Create an array of indices
b = np.array([0,2,0,1])

#Select one element from each row of a using indices in b

print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices of b

a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [48]:
#Boolean array indexing, lets you pick out arbitrary elements of an array. Frequently this type of indexing
#is used to select the elements of an array that satisfy some condition

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2) # Find the elements of a that are bigger than 2; returns a numpy array

print(bool_idx)

print(a[bool_idx])
print(a[a > 2])


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [53]:
# DATATYPES

# Every numpy array is a grid of elements in the same type. Numpy provides a large set of numeric datatypes
#that we can use to construct arrays, Numpy tries to guess a datatype when you create an array, but functions that
#construct arrays usually also include an option to specify the datatype

x = np.array([1,2])
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1,2], dtype=np.float64)
print(x.dtype)

print(x)

int64
float64
float64
[ 1.  2.]


In [69]:
#ARRAY MATH

#Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x / y)
print(np.divide(x,y))

print(np.sqrt(x))

# * is elementwise multiplication not matrix multiplication. We use the dot function to compute the inner product of vectors

# INNER PRODUCT OF VECTORS PRODUCE 219

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))

# MATRIX / VECTOR product; both produce a rank 1 array

print(x.dot(v))
print(np.dot(x,v))

# matrix / matrix product

print(x.dot(y))
print(np.dot(x,y))

#Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0)) # Compute sum of each column; prints "[4 6]" 
print(np.sum(x, axis=1)) # Compusde sum of each row


#We may reshape or manipulate data in arrays, for example the transpose

print(x)
print(x.T)

#Taking the transpose of a rank 1 matrix does nothing

v = np.array([1,2,3])
print(v)
print(v.T)

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]
219
219
[ 29.  67.]
[ 29.  67.]
[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]
10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [79]:
# BROADCASTING

#Frequently we have a smaller array and a bigger array, we want to use the smaller array multiple times to perform
#an operation in the large array

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # Create an empty matrix with the shape of x

#add the vector v to each row of the matrix x with an explicit loop

for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)

#However this is a slow approach, it is better to create a matrix that does this and do element wise 

vv = np.tile(v, (4,1))

y = x + vv
print (y)


#However numpy broadcasting allow us to do this without stacking multiple copies of v

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

#Examples of broadcasting

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]

print(np.reshape(v, (3,1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
print(v)
print(x)
print(x + v)


# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]

print((x.T + w).T)

# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.

print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 4  5]
 [ 8 10]
 [12 15]]
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
